### ISSUE TITLE
WARNING: Cookiebot script is included twice and TypeError: Cannot read property 'readyState' of null

### ISSUE THREAD

**Issue by donnysmit** [yeutech-lab/react-cookiebot#16]
## Issue Type

Bug

## Description

When I use CookieBot with React as described in the docs, it tells me that I have it included twice.
I checked if I had it in my app twice, but there's only one CookieBot component in there.
This also causes an error in console when the user clicks on the button in the CookieBot UI.
When I check the HTML it indeed has included CookieBot twice.
`<script id="CookieBot" src="https://consent.cookiebot.com/uc.js" data-cbid="myId" data-blockingmode="auto" type="text/javascript"></script>`
`<script id="CookieBot" src="https://consent.cookiebot.com/uc.js" data-cbid="myId" data-blockingmode="auto" type="text/javascript"></script>`

The console returns this in order:
`1. WARNING: Cookiebot script is included twice - please remove one instance to avoid unexpected results.`
`2. ui.click: div#CybotCookiebotDialogBodyLevelDetailsWrapper`
`3. TypeError: Cannot read property 'readyState' of null`

My CookieBot code in app.tsx:

`import CookieBot from "react-cookiebot";`

`<CookieBot domainGroupId={"myId"} />`

# Versions

- Node/NPM: 12.16.3
- OS: Windows 10, Mac OS X 10.15.4
- react-cookiebot: 1.0.8

**Comment by jackdewhurst** [comment]
I have the same issue on Chrome, Firefox and IE/Edge.

This lib also causes my site to load a blank white page on IE9-11, not sure if it's related to the double declaration issue or something else.. Is IE supported?

**Comment by donnysmit** [comment]
> This lib also causes my site to load a blank white page on IE9-11, not sure if it's related to the double declaration issue or something else.. Is IE supported?

I just checked this, while the cookies ui is opened I have the same problem. The plugin probably doesn't have polyfill either.

**Comment by kopax** [comment]
Hi guys. I am using it in production without issue. Is your component rendered more than once ? It shouldn't. 

Regarding polyfill, I wonder why would we need that. Have you checked the source code ? It only create the js element once using vanilla JS. I am on Linux and don't have IE. If polyfill are necessary, a PR from one who can test and fix is welcome.

May you share the link of your app?

**Comment by jackdewhurst** [comment]
I eventually got it working without warnings and on IE by ignoring this plugin and using the steps directly from Cookiebot's site, adding the scripts manually etc..

Tried this plugin in a couple of react apps and the double declaration issue is present in both, followed the instructions to the letter..

**Comment by kopax** [comment]
Hi @jackdewhurst , I think you took the right decision if you are having issue with this integration. This is here to help, not to make things worst. 

Now that I am aware of the IE issue, I'll be watching it and I'll fix if I get over this myself, unless I have enough reports from IE users.

> Tried this plugin in a couple of react apps and the double declaration issue is present in both, followed the instructions to the letter..


Regarding the double injection, I think you are clearly having error in all your websites, if you are well aware of vanilla JS, check this source code:

https://github.com/yeutech-lab/react-cookiebot/blob/264443b86d8d4d992bbe1e74024a3954585da537/src/CookieBot.js#L26

It means this line is being run twice, so you **must** have a rerender issue, you can check with the developer tool, this might cause serious lags with or without this library. `useEffect` may help you prevent re-rendering for just this component thought this won't also be the right fix.

I can avoid this to be injected twice by checking if the id is already present, but the right fix here would be not to re-render your main component twice.

I'll add a warning on the documentation such as :

> You must add this at the root of your website or make sure your parent component does not re-rerender otherwise you'll get ` WARNING: Cookiebot script is included twice - please remove one instance to avoid unexpected results.` and this will break cookiebot

**Comment by kopax** [comment]
Fixed by #22
