### ISSUE TITLE
Server Side Rendering

### ISSUE THREAD

**Issue by SilentImp** [yeutech-lab/react-cookiebot#17]
## Issue Type

- [ ] [Feature](https://github.com/yeutech-lab/react-cookiebot/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description
Would it be possible to do server-side rendering for Cookie Declaration?
Also, it looks like the script does not add a declaration in case of client-side navigation.

**Comment by kopax** [comment]
1. I do not do server side rendering but I am sure it's possible. PR are welcome
2. I do not get the client side navigation remarks. Do you mind to elaborate ?

**Comment by kopax** [comment]
Fixed by #24 and #25
