### ISSUE TITLE
Add support to "consent banner/dialog" language (data-culture parameter)

### ISSUE THREAD

**Issue by situplastik** [yeutech-lab/react-cookiebot#19]
## Issue Type

- [x] Add `language` param on CookieBot declaration props

## Description

As Cookiebot [explain on their website](https://support.cookiebot.com/hc/en-us/articles/360003793394-How-do-I-set-the-language-of-the-consent-banner-dialog-), if you have a Domain group consent configurated with many languages, you can set witch language consent you want yo show or put on auto-detect. Most of the times auto-detect is enought, buy if you have a multi-language site would be interested to force to use the language that you are seeing the rest of the website.

# Versions

- react-cookiebot: 1.0.8

**Comment by kopax** [comment]
Thanks, that make perfect sens. PR is welcome, otherwise I'll try to do it soon or later. Do you have a clue on how to solve the Gatsby support ?

**Comment by situplastik** [comment]
I've just create a PR in order to solve that issue.

Yes, the issue related to Gatsby and another about Server Side rendering is for the same problem. I would create a PR as soon as we solve that issue ;)

**Comment by kopax** [comment]
Great, I had a look, I am watching the build to see if it can pass the lint. There's also one point that need to be reviewed, check my comment. 

Thanks by all for your contribution!

**Comment by kopax** [comment]
Fixed in `v1.0.9`
